### ISSUE TITLE
Error reading registry: wrong params

### ISSUE THREAD

**Issue by sinkcup** [solemnwarning/ipxwrapper#26]
I have two PCs with Red alter 2, at first time, they can play in lan.

after I stop the mission, and create a new game, then it malfunctioned.

- left PC: Win 10 x64, can see the right player in lobby, but can't see games which created by the right player
- right PC: Win 11 x64, can't see the left player in lobby, and can't see games which created by the left player

all firewalls of the two PCs are off.

the `ipxwrapper.log` of the right PC:

```
[1188.18, thread 4892] Error reading registry: 参数错误。
[1188.21, thread 4892] Error reading registry: 参数错误。
[1188.21, thread 4892] IPXWrapper 0.7.1
[1188.21, thread 4892] Compiled at Fri 5 Jul 21:46:03 BST 2024
[1188.21, thread 4892] Performance counter: 10000000 Hz
[1188.21, thread 4892] Adding exception to Windows Firewall
[1188.21, thread 4892] Cannot add firewall exception, not running as an administrator
[1188.21, thread 4892] --
[1188.23, thread 4892] Listing IP interfaces:
[1188.23, thread 4892] --
[1188.23, thread 4892] AdapterName:   {6917DBD6-6429-4C7C-8A54-B26B76F27A45}
[1188.23, thread 4892] Description:   MediaTek Wi-Fi 6/6E Wireless LAN Card
[1188.23, thread 4892] AddressLength: 6
[1188.23, thread 4892] Address:       70:C9:12:1C:1C:17
[1188.23, thread 4892] Index:         11
[1188.23, thread 4892] Type:          71
[1188.23, thread 4892] DhcpEnabled:   1
[1188.23, thread 4892] IpAddress:     192.168.31.17
[1188.23, thread 4892] IpMask:        255.255.255.0
```

![d03aaf69f5b4090b4f7cdee41e663f8](https://github.com/user-attachments/assets/40ab9cb1-a83b-42e6-bfec-f5765461c05f)

**Comment by sinkcup** [comment]
the left PC has the same error log:

```
[3525.12, thread 16092] Error reading registry:  参数错误。
[3525.17, thread 16092] wsock32.dll:WSAStartup -> wsock32.dll
[3525.17, thread 16092] wsock32.dll:EnumProtocolsA -> ipxwrapper.dll
[3525.17, thread 16092] Error reading registry:  参数错误。
[3525.18, thread 16092] IPXWrapper 0.7.1
[3525.18, thread 16092] Compiled at Fri 5 Jul 21:46:03 BST 2024
[3525.18, thread 16092] Performance counter: 10000000 Hz
[3525.18, thread 16092] Adding exception to Windows Firewall
```

**Comment by solemnwarning** [comment]
Hi there,

Are you using Windows XP compatibility mode? I've only seen that registry error in compatibility mode, it should be fixed in this build:

[ipxwrapper-git.zip](https://github.com/user-attachments/files/18154167/ipxwrapper-git.zip)

Were there any other errors listed in the log on either machine?

**Comment by sinkcup** [comment]
I have tried the new zip and compatibility mode win7 on the win 10 PC, there is no more error but still can't be found by other players such as win 11.

I have tried a win8.1 PC vs win11 PC, the RA2 lan is fine.

![96c1e7b28e5fff530205c5eac88ad53](https://github.com/user-attachments/assets/f74e24af-af3f-43ce-b26a-f09cf5c4c088)

**Comment by solemnwarning** [comment]
I've played a few "games" of RA2 between a Windows 10 and Windows 11 machine and not been able to reproduce this. I tried aborting the mission and immediately starting a new lobby and also restarting the game.

What exact steps are you going through?
